service: testaws
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  createPhone:
    handler: src/phone/createPhone.create
    events:
      - http:
          path: phones
          method: post
          
  getPhone:
    handler: src/phone/getPhone.get
    events:
      - http:
          path: phones
          method: get
          
