service: testaws
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:816694965331:table/PhoneTable

functions:
  createPhone:
    handler: src/phone/createPhone.create
    events:
      - http:
          path: phones
          method: post

  getPhone:
    handler: src/phone/getPhone.get
    events:
      - http:
          path: phones
          method: get

  updatePhone:
    handler: src/phone/updatePhone.update
    events:
      - http:
          path: phones
          method: put

  deletePhone:
    handler: src/phone/deletePhone.deletePhone
    events:
      - http:
          path: phones
          method: delete          

resources:
  Resources:
    PhoneTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PhoneTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH 